export const incomeStatement = [
    { displayName: 'Fiscal Year End Date', dataName: 'fiscalDateEnding' },
    { displayName: 'Gross Profit', dataName: 'grossProfit' },
    { displayName: 'Total Revenue', dataName: 'totalRevenue' },
    { displayName: 'Cost of Revenue', dataName: 'costOfRevenue' },
    { displayName: 'Cost of Goods and Services Sold', dataName: 'costofGoodsAndServicesSold' },
    { displayName: 'Operating Income', dataName: 'operatingIncome' },
    { displayName: 'Selling, General and Administrative', dataName: 'sellingGeneralAndAdministrative' },
    { displayName: 'Research and Development', dataName: 'researchAndDevelopment' },
    { displayName: 'Operating Expenses', dataName: 'operatingExpenses' },
    { displayName: 'Investment Income Net', dataName: 'investmentIncomeNet' },
    { displayName: 'Net Interest Income', dataName: 'netInterestIncome' },
    { displayName: 'Interest Income', dataName: 'interestIncome' },
    { displayName: 'Interest Expense', dataName: 'interestExpense' },
    { displayName: 'Non-Interest Income', dataName: 'nonInterestIncome' },
    { displayName: 'Other Non-Operating Income', dataName: 'otherNonOperatingIncome' },
    { displayName: 'Depreciation', dataName: 'depreciation' },
    { displayName: 'Depreciation and Amortization', dataName: 'depreciationAndAmortization' },
    { displayName: 'Income Before Tax', dataName: 'incomeBeforeTax' },
    { displayName: 'Income Tax Expense', dataName: 'incomeTaxExpense' },
    { displayName: 'Interest and Debt Expense', dataName: 'interestAndDebtExpense' },
    { displayName: 'Net Income From Continuing Operations', dataName: 'netIncomeFromContinuingOperations' },
    { displayName: 'Comprehensive Income Net of Tax', dataName: 'comprehensiveIncomeNetOfTax' },
    { displayName: 'EBIT', dataName: 'ebit' },
    { displayName: 'EBITDA', dataName: 'ebitda' },
    { displayName: 'Net Income', dataName: 'netIncome' },
];

export const balanceSheet = [
    { displayName: 'Fiscal Year End Date', dataName: 'fiscalDateEnding' },
    { displayName: 'Total Assets', dataName: 'totalAssets' },
    { displayName: 'Total Current Assets', dataName: 'totalCurrentAssets' },
    { displayName: 'Cash and Cash Equivalents at Carrying Value', dataName: 'cashAndCashEquivalentsAtCarryingValue' },
    { displayName: 'Cash and Short Term Investments', dataName: 'cashAndShortTermInvestments' },
    { displayName: 'Inventory', dataName: 'inventory' },
    { displayName: 'Current Net Receivables', dataName: 'currentNetReceivables' },
    { displayName: 'Total Non Current Assets', dataName: 'totalNonCurrentAssets' },
    { displayName: 'Property Plant Equipment', dataName: 'propertyPlantEquipment' },
    { displayName: 'Accumulated Depreciation Amortization PPE', dataName: 'accumulatedDepreciationAmortizationPPE' },
    { displayName: 'Intangible Assets', dataName: 'intangibleAssets' },
    { displayName: 'Intangible Assets Excluding Goodwill', dataName: 'intangibleAssetsExcludingGoodwill' },
    { displayName: 'Goodwill', dataName: 'goodwill' },
    { displayName: 'Investments', dataName: 'investments' },
    { displayName: 'Long Term Investments', dataName: 'longTermInvestments' },
    { displayName: 'Short Term Investments', dataName: 'shortTermInvestments' },
    { displayName: 'Other Current Assets', dataName: 'otherCurrentAssets' },
    { displayName: 'Other Non Current Assets', dataName: 'otherNonCurrentAssets' },
    { displayName: 'Total Liabilities', dataName: 'totalLiabilities' },
    { displayName: 'Total Current Liabilities', dataName: 'totalCurrentLiabilities' },
    { displayName: 'Current Accounts Payable', dataName: 'currentAccountsPayable' },
    { displayName: 'Deferred Revenue', dataName: 'deferredRevenue' },
    { displayName: 'Current Debt', dataName: 'currentDebt' },
    { displayName: 'Short Term Debt', dataName: 'shortTermDebt' },
    { displayName: 'Total Non Current Liabilities', dataName: 'totalNonCurrentLiabilities' },
    { displayName: 'Capital Lease Obligations', dataName: 'capitalLeaseObligations' },
    { displayName: 'Long Term Debt', dataName: 'longTermDebt' },
    { displayName: 'Current Long Term Debt', dataName: 'currentLongTermDebt' },
    { displayName: 'Long Term Debt Noncurrent', dataName: 'longTermDebtNoncurrent' },
    { displayName: 'Short Long Term Debt Total', dataName: 'shortLongTermDebtTotal' },
    { displayName: 'Other Current Liabilities', dataName: 'otherCurrentLiabilities' },
    { displayName: 'Other Non Current Liabilities', dataName: 'otherNonCurrentLiabilities' },
    { displayName: 'Total Shareholder Equity', dataName: 'totalShareholderEquity' },
    { displayName: 'Treasury Stock', dataName: 'treasuryStock' },
    { displayName: 'Retained Earnings', dataName: 'retainedEarnings' },
    { displayName: 'Common Stock', dataName: 'commonStock' },
    { displayName: 'Common Stock Shares Outstanding', dataName: 'commonStockSharesOutstanding' },
    { displayName: 'Net Income', dataName: 'netIncome' }
];

export const cashFlowStatement = [
    { displayName: 'Fiscal Year End Date', dataName: 'fiscalDateEnding' },
    { displayName: 'Operating Cashflow', dataName: 'operatingCashflow' },
    { displayName: 'Payments for Operating Activities', dataName: 'paymentsForOperatingActivities' },
    { displayName: 'Proceeds from Operating Activities', dataName: 'proceedsFromOperatingActivities' },
    { displayName: 'Change in Operating Liabilities', dataName: 'changeInOperatingLiabilities' },
    { displayName: 'Change in Operating Assets', dataName: 'changeInOperatingAssets' },
    { displayName: 'Depreciation, Depletion and Amortization', dataName: 'depreciationDepletionAndAmortization' },
    { displayName: 'Capital Expenditures', dataName: 'capitalExpenditures' },
    { displayName: 'Change in Receivables', dataName: 'changeInReceivables' },
    { displayName: 'Change in Inventory', dataName: 'changeInInventory' },
    { displayName: 'Profit/Loss', dataName: 'profitLoss' },
    { displayName: 'Cashflow from Investment', dataName: 'cashflowFromInvestment' },
    { displayName: 'Cashflow from Financing', dataName: 'cashflowFromFinancing' },
    { displayName: 'Proceeds from Repayments of Short Term Debt', dataName: 'proceedsFromRepaymentsOfShortTermDebt' },
    { displayName: 'Payments for Repurchase of Common Stock', dataName: 'paymentsForRepurchaseOfCommonStock' },
    { displayName: 'Payments for Repurchase of Equity', dataName: 'paymentsForRepurchaseOfEquity' },
    { displayName: 'Payments for Repurchase of Preferred Stock', dataName: 'paymentsForRepurchaseOfPreferredStock' },
    { displayName: 'Dividend Payout', dataName: 'dividendPayout' },
    { displayName: 'Dividend Payout (Common Stock)', dataName: 'dividendPayoutCommonStock' },
    { displayName: 'Dividend Payout (Preferred Stock)', dataName: 'dividendPayoutPreferredStock' },
    { displayName: 'Proceeds from Issuance of Common Stock', dataName: 'proceedsFromIssuanceOfCommonStock' },
    { displayName: 'Proceeds from Issuance of Long Term Debt and Capital Securities (Net)', dataName: 'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet' },
    { displayName: 'Proceeds from Issuance of Preferred Stock', dataName: 'proceedsFromIssuanceOfPreferredStock' },
    { displayName: 'Proceeds from Repurchase of Equity', dataName: 'proceedsFromRepurchaseOfEquity' },
    { displayName: 'Proceeds from Sale of Treasury Stock', dataName: 'proceedsFromSaleOfTreasuryStock' },
    { displayName: 'Change in Cash and Cash Equivalents', dataName: 'changeInCashAndCashEquivalents' },
    { displayName: 'Change in Exchange Rate', dataName: 'changeInExchangeRate' },
    { displayName: 'Net Income', dataName: 'netIncome' },
];